prefix: "&8[&9KimiVanish&8]"

settings:
  vanish:
    bossbar: true
    actionbar: false
    protect-players: true
    protect-recently-unvanished: true
    hide-connection-message: true
    prevent-hunger-loss: true
    use-gui-list: true

messages:
  vanish:
    set-level:
      deny:
        lowest-level: "&cYou are currently at the lowest level."
        not-integer: "&cYou haven't entered a valid number."
        not-available: "&cYou cannot access this level as it is higher than yours."
      allow: "&aYou have been vanished at level {0}"
    list:
      chat: "&f &9Level {0}:&8 - &7{1}"
      empty: "&cNo one is currently in vanish."
    help:
      setting-header: "&9Setting Subcommands"
      general-header: "&9Commands"
      commands: "&9/{0} {1} &8- &7{2}"
    bossbar: "&c&lYOU ARE IN VANISH"
    unhide-all: "&cA plugin reload has forced you to become visible."
    hideother: "&7You have hidden &a{0}&7 at level &a{1}"
    hideother-other: "&7You were hidden at level &a{0} &7by &a{1}"
    hide: "&aYou have been hidden at level &2{0}"
    unhide: "&cYou are now visible to all players"
    item:
      on: "&7You have toggled item pickup & drop &aON"
      off: "&7You have toggled item pickup & drop &cOFF"
    interact:
      on: "&7You have toggled physical interactions &aON"
      off: "&7You have toggled physical interactions &cOFF"
    notify:
      player-unvanished: "&7Player {0} has unvanished."
      player-vanished: "&7Player {0} has vanished at level {1}"
      on: "&7You have toggled notifications &aON"
      off: "&7You have toggled notifications &cOFF"
    location:
      saved: "&7Saved your vanish entry location as &9{0}x {1}y {2}z&7."
      teleported: "&7Your vanish entry location was saved, so you have been teleported."
      on: "&7You have toggled location saving &aON"
      off: "&7You have toggled location saving &cOFF"
    nightvision:
      on: "&7You have toggled nightvision &aON"
      off: "&7You have toggled nightvision &cOFF"
    flight:
      on: "&7You have toggled nightvision &aON"
      off: "&7You have toggled nightvision &cOFF"
    confirm-message: "&7You sent the message: &9{0}&7. Did you mean to do this? If so, &9resend the same message&7."